import "./globals.css";

import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import { Navbar } from "~/components/navbar";
import { ThemeProvider } from "~/components/theme-provider";

import type { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }: PropsWithChildren<unknown>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
